all:
	g++ -o ConsumerCompile ConsumerCompile.cc `root-config --glibs --cflags ` -lNew
	g++ -o ProducerCompile ProducerCompile.cc `root-config --glibs --cflags ` -lNew
	g++ -o ConsumerCompile_withSocketServer ConsumerCompile_withSocketServer.cc `root-config --glibs --cflags ` -lNew
	g++ -o Viewer_withSocketClient Viewer_withSocketClient.cc `root-config --glibs --cflags ` -lNew
